const express = require("express");
const router = express.Router();
const admin = require("../controller/adminController");
const upload = require("../helper/multer");
const auth = require("../helper/token");
router.post("/login", admin.login);
router.post("/register", admin.register);
router.post("/invite",auth, admin.inviteEmployee);
router.get("/allEmployees",auth, admin.allEmployees);
router.post('/markLogin', auth, admin.markLogin);
router.post('/markLogout', auth, admin.markLogout);
router.post("/employee/attendance", auth, admin.getEmployeeAttendance);
router.post("/employee", auth, admin.getSingleEmployee);
router.post("/createProject", auth, upload.single('projectImage'), admin.createNewProject);
router.get("/projects", auth,admin.getAllProjects);
router.get("/project/:projectId", auth,admin.getProjectDetails);
router.get("/project/getBugCount/:projectId", auth,admin.getStatusCount);
router.post("/project/bugs", auth, admin.getBugs);
router.get('/bug/:bugId',auth,admin.bugDetails);
router.get('/bug/history/:bugId', auth, admin.getHistory);
module.exports = router;
