const express = require("express");
const router = express.Router();
const employee = require("../controller/employeeController");
const auth = require("../helper/token");
const upload = require("../helper/multer");
router.post("/register", employee.register);
router.post("/login", employee.login);
router.get("/profile", auth, employee.getDetails);
router.put("/profileUpdate", auth, upload.single('profileImg'), employee.updateProfile);
router.put("/markLogin", auth, employee.markLogin);
router.put("/markLogout", auth, employee.markLogout);
router.get("/home", auth, employee.home);
router.get("/attendances", auth,employee.getEmployeeAttendance);
router.get('/getRole',auth, employee.getRole);
router.get("/projects",auth, employee.getAllProjects);
router.post('/project/bug', auth, employee.getBugs);
router.get("/project/:projectId",auth,employee.getProjectDetails);
router.post('/newBug',auth,upload.any() ,employee.raiseBug);
router.get('/allEmployees',auth, employee.allEmployees);
router.get('/bug/:bugId',auth,employee.bugDetails);
router.post('/addComment',auth,employee.addComment);
router.get('/bug/comments/:bugId',auth,employee.getAllComments);
router.post('/bug/updateStatus',auth,employee.updateBugStatus);
router.get('/project/getBugCount/:projectId',auth,employee.getStatusCount);
router.get('/bug/history/:bugId', auth, employee.getHistory);
// router.post('/filterBugs',auth,employee.getFilteredBugs);
module.exports = router
